# All About Classes

### Objects and Classes

1. Everything physical can be represented as the sum of objects.
2. Objects Store information in themselves (As their state)
3. Most Objects can be generalized

Before we delve into any actual programming imagine pick any real world object around you. It stores information (color, shape, ect.) in it's state and is also likley made up of other sub-objects. If you know what to call it then that means that it also can be generalized into a greater class.

You -> Human -> Object
Dog -> Animal -> Object
Alien -> Organism -> Object
Meteor -> Spatial Bodies -> Object

We can also go the other way (which is how objects are usually created)

Human -> You 
Animal -> Dog
Organism -> Alien
Spatial Bodies -> Meteor

### basic class that does nothing and stores nothing

In [46]:
class Basic():
    pass

Defining a class is a lot like defining a function you type in class [classname](inhertedobjects):  to start a class past the indent

### Functions and Classes

In [24]:
class Dog():
    def bark():
        return "barking"
    def Isscared():
        return False

We can put functions inside of classes to give the objects created from these classes things to do. The resulting dog object in this case can bark

### The __init__ function

In [51]:
class Dog():
    def __init__(self,fur_color,age):
        self.fur_color = fur_color
        self.age = age
    def bark(self):
        return "barking"
    def scared(self):
        return False
    def eat(self):
        return 20-self.age

By using the __init__ function we can store properties about the dog inside of it when it is created

In the example above we store the age and the fur_color

## Making an Object

In the code above we defined how to make a dog, but never actually made one to actually make one you have to run the line below

In [52]:
myDog = Dog("orange",4)

In [53]:
myDog.eat()

16

### Excercise 1

Make me a new class called car give it number of wheels (in the init function) and add a drive function

In [54]:
class Car():
    def __init__(self,wheels):
        self.wheels = wheels
    def drive(self):
        return "Driving"

### Excercise 2

Make a class called employee with an age and a height and travel distance

In [60]:
class Employee():
    def __init__(self,age, height, travel):
        self.age = age
        self.height = height
        self.travel = travel

Now Make a company class where I specify the number of Employees by giving a list of charechteristics. Plug this into a Company class with a list of the generated employees.

In [61]:
employee_List = [[21,70,1],[17,71,10],[23,60,10]]

class Company():
    def __init__(self,employee_features):
        self.employees = []
        for prospecting_employee in employee_features:
            age = prospecting_employee[0]
            height = prospecting_employee[1]
            travel = prospecting_employee[2]
            self.employees.append(Employee(age,height,travel))
            
Ls = Company(employee_List)
Ls.employees

## Special Class Functions


In [49]:
class Number():
    def __init__(self,n :int):
        self.n = n
    def __add__(self,n):
        return Number(self.n+n.n)
    def __sub__(self,n):
        return Number(self.n-n.n)
    def __mul__(self,n):
        return Number(self.n*n.n)
    def __truediv__(self,n):
        return Number(self.n/n.n)
    def __floordiv__(self,n):
        return Number(self.n/n.n)

In [54]:
One = Number(1)
Two = Number(2)

In [58]:
print((One/Two).n)

0.5


An example of special class functions. They start with two underscores and are called under special conditions in python

In [60]:
class ListWrapper():
    def __init__(self,myList):
        self.myList = myList
    def __getitem__(self,n):
        return self.myList[n]
    def __setitem__(self,n,inp):
        self.myList[n] = inp

In [61]:
M = ListWrapper([1,2,3,2,1])

In [45]:
M[0:3]


[1, 2, 3]

In [46]:
M[0] = 2

In [47]:
for i in M:
    print(i)

2
2
3
2
1


### Practice

Make me a class called square that can find its own area for a given a side-length

In [76]:
class Square():
    def __init__(self,side_length):
        self.sl = side_length
    def find_area(self):
        return self.sl**2

In [78]:

A = int(input("Square Length:"))
Sq = Square(A)
print(Sq.find_area())
print(Sq)


Square Length:10
100


Make a house with a size, number of doors, and a special class function add that adds size and number of doors.

In [83]:
class House():
    def __init__(self,size,door_count):
        self.size = size
        self.door_count = door_count
    def __add__(self,other):
        return House(self.size+other.size,self.door_count+other.door_count)

In [85]:
H = House(10,10)+House(10,10)

In [88]:
(H.size,H.door_count)

(20, 20)

In [91]:
["A","B","C"]

['A', 'B', 'C']

In [106]:
A = {1,3,2,2}
print(A)

{1, 2, 3}


In [109]:
A = dict()
A["Cat"] = 0
A["Dog"] = 1
A["Bird"] = 2

In [113]:
print(A)
print(A["Cat"])

{'Dog': 1, 'Bird': 2, 'Cat': 0}


KeyError: ('Cat', 'Dog')

Pick three words and write down their denenitions in a dictionary

In [114]:
import numpy as np

In [119]:
print(np.array([[1,2,3],[1,2,3]]))
print(np.zeros((10,10)))
print(np.ones((10,10)))

[[1 2 3]
 [1 2 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [126]:
np.random.normal(size=(10,10))

array([[ 0.71347735,  0.90064298,  0.64667969,  0.38196587, -0.42308235,
         0.47517565, -0.87340051,  0.85603858,  0.79892755, -1.56731353],
       [ 0.9760204 ,  0.30385777, -1.62737828,  0.91963799,  0.3473697 ,
         0.78914547,  0.64978512,  1.14385082,  1.52653285,  1.79347214],
       [-1.25230275,  0.60909889,  1.17386834,  1.1963373 , -0.32769881,
        -2.69483443, -2.57115011,  0.90387595,  1.39105392, -1.30551001],
       [-0.2929762 , -1.79878481, -0.71249284, -0.63268425,  1.04948878,
        -1.41398763, -0.87657135,  1.22254961, -0.91738313, -0.65072219],
       [ 2.51496233,  0.57965229, -1.96394109,  0.25199568, -0.49162708,
        -1.01066917, -0.19964206, -0.5705831 ,  1.06462784,  0.25234137],
       [-0.31820568, -1.27906919,  0.03087226, -1.40410256,  1.11784308,
        -0.32940081,  1.41206074, -1.24789023, -0.04948761, -0.49992448],
       [ 1.4249281 , -0.53040782,  0.23868766,  0.61056505,  0.50194387,
        -0.40922714, -1.45206595, -1.35891231

Make a gameboard for a new game. The first layer is the peices (zeroes). The second layers is the resources random. The third layer is ones.

In [145]:
First_layer = np.zeros((10,10))
Second_layer = np.random.normal(size=(10,10))
Third_layer = np.ones((10,10))

In [151]:
stacked = np.stack((First_layer,Second_layer,Third_layer))

In [152]:
stacked.shape

(3, 10, 10)

In [155]:
print(stacked[1,0,0])

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 1.8697648  -0.12049569  0.00263575  0.95945487 -0.40945573  0.68870718
  -1.49553281  0.0862167   0.19739461 -1.06848789]
 [ 1.          1.          1.          1.          1.          1.
   1.          1.          1.          1.        ]]


ImportError: No module named 'matplotlib'